apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
    name: nginx-secret
spec:
  containers:
    - image: nginx
      name: nginx-secret
      resources: {}
      env:
        - name: COOL_VARIABLE
          valueFrom:
            secretKeyRef:
              name: another-secret
              key: key1
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
